version: '3.8'
services:
  receiver-service:
    build: ./receiver-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pubsub
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  listener-service:
    build: ./listener-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/pubsub
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

volumes:
  mongo-data:
